### PR TITLE
Adjusted phrase to clarify the learning objective

### PR DESCRIPTION
**Pull request by ndjones**
The phrasing was slightly confusing, as the second part might have referred to the program, rather than the assertions.

### CODE REVIEW

**Comment by kynan** [comment]
Makes sense to me.

**Comment by ewanbarr** [comment]
This appears to be grammatically incorrect (mix of singular and plural and an incorrect use of the work "which") and should really just read:

Add assertions to a program that checks the program's state is correct.

**Comment by ndjones** [comment]
Agree .. the further refinement of plural to singular is required, good catch - I hadn't noticed that.

The problem with the suggested phrasing is that the "that" refers to the noun that precedes it, in this case the word program. Changing it to ", which" does make the qualifier at the end non-restrictive so perhaps changes the intended meaning .. though it then reads correctly as simply a clause to provide further information on the first clause.

Perhaps either of the following would work..
- Add assertions to a program, which check the program's state is correct.
- Add assertions that check the program's state is correct.

**Comment by ewanbarr** [comment]
Either of those work for me.

**Comment by abostroem** [comment]
@ndjones Please update this with either statement so we can merge this PR

**Comment by kynan** [comment]
I think this is good to go now.

**Pull request merged**
