### PR TITLE
Adds solution to challenge `Stacking Arrays` in episode one

### PR DESCRIPTION
**Pull request by itcarroll**
This is my first PR for a Software Carpentry lesson, so please don't hesitate to correct my procedure.

The way I interpreted the challenge, it is necessary for the trainee to avoid removal of singleton dimensions that can result from indexing. I don't think the solution gets ahead of future lessons, but perhaps an maintainer could say?

### CODE REVIEW

**Comment by valentina-s** [comment]
Thank you for the contribution! 
Your solution is ok (I suspect the array indexing would look a bit like a magic to a novice, but I do not see much better alternative). Another option is to explain that the stacking functions treat the one dimensional arrays as row vectors, so to obtain the desired result we need 

`numpy.vstack([A[:,0],A[:,-1]]).T`

Unfortunately, I realized transposing has not been introduced in this part yet, so it would require a brief explanation. So if you wish you can add it as an alternative.

**Comment by itcarroll** [comment]
I guess array indexing had only been used with slices in the lesson, so I replaced the `A[:, [0]]` with the equivalent `A[:, :1]` and likewise for the last column. That shouldn't be introducing anything new into the challenge solution. (Transposing, as you note, would be a new topic.)

**Comment by valentina-s** [comment]
I like this solution! Could you just replace the above appearance of A[:,[0]] with A[:,:1], and I will merge.

**Comment by valentina-s** [comment]
Thanks!

**Pull request merged**
