### PR TITLE
Update sample code files to py3k

### PR DESCRIPTION
**Pull request by abought**
## Purpose
Per #127 , we would like to update these lessons to work with python 3. Might as well start somewhere!

## Summary of changes
All example files (mainly used in `10-cmdline.md`) have been updated to work with both Python 2 *and* 3. Sample code inside the markdown file has been updated accordingly. 

These changes were fairly minor, and mainly required using `print` as a function instead of a statement.

Minor changes were also made for PEP-8. The HTML was regenerated from `make preview`.

## Side effects/ Quirks
The sample code embedded in the lessons does not actually include `from __future__ import print_function`, mainly to reduce confusion while teaching the lesson. This statement is used in the runnable code files to ensure that things run with both Python 2 and 3 during the transition period.

No other lesson files were converted in this PR.

### CODE REVIEW

**Comment by abought** [comment]
Just to bring up to date:

There was talk of creating an official Python 3 branch, to keep changes separate until the entire lesson had been converted. Is that a thing? If so, should I resubmit the PR there?

@gvwilson had proposed that we make the lessons *either* python 3 or 2, rather than target dual compatibility. I'm happy to revise and resubmit accordingly; just let me know what and where. :)

**Comment by gvwilson** [comment]
We now have a `py3k` branch - please start submitting PRs there to 
upgrade the lesson.

**Comment by r-gaia-cs** [comment]
@abostroem Thanks for all the work. This is super seeded by #142.

**Comment by abostroem** [comment]
@r-gaia-cs Just checking that your comment means we can close this PR

**Comment by r-gaia-cs** [comment]
> Just checking that your comment means we can close this PR

@abostroem Yes.

**Comment by abought** [comment]
Great to see the conversion moving along!

**Pull request closed without merging**
