### PR TITLE
Update python-sticky-note-variables* figures

### PR DESCRIPTION
**Pull request by maxim-belkin**
Updating SVG figures

### CODE REVIEW

**Comment by annefou** [comment]
I like the new figures! 
Stupid question but do we keep both .svg and .odg files?

**Comment by maxim-belkin** [comment]
I'm removing corresponding .odg files in this PR and will add a README.md to that folder later on how to work with SVG files.

**Comment by annefou** [comment]
Yes that would be great to give good recommendation on how to work with SVG. (I don't know myself...).

**Comment by maxim-belkin** [comment]
I've added a `README.md` file to the `fig` directory with basic guidelines on how to use third-party editors.

**Pull request merged**
