### PR TITLE
Reword exercise

### LINKED ISSUE #454: Confusing exercise wording
Ep1 check your understanding

> Draw diagrams showing what variables refer to what values after each statement in the following program:

It seems strange to request a diagram. Rather, 'write down what you expect the answer to be' would seem to be a more sensible wording?

### PR DESCRIPTION
**Pull request by gcapes**
Fix #454.

### CODE REVIEW

**Comment by maxim-belkin** [comment]
Thanks @gcapes! Could you please also fix the next sentence in this PR?

> You can test your answers by typing the commands.

? "typing" does not test answers. "executing" does :)

**Comment by maxim-belkin** [comment]
I'd also suggest removing "You can". Invite attendees to test their answers:

> Test your answers by executing the above commands

@MikeTrizna what are your thoughts on this one?

**Comment by MikeTrizna** [comment]
I agree that in general, "execute" is much clearer command than "type".  I also see that this distinction came up in https://github.com/swcarpentry/python-novice-inflammation/commit/e685495.

**Comment by maxim-belkin** [comment]
Thanks, @gcapes!
Is this PR part of your instructor checkout process?

**Comment by gcapes** [comment]
No worries!
We've never met but I maintain the Make lesson, so nope, this isn't for instructor checkout.

**Comment by gcapes** [comment]
Oops! Wrong button there!

**Comment by maxim-belkin** [comment]
I think "Close pull request" button should be red AND on the left side :)
Thanks for your contribution, Gerard!

**Pull request closed without merging**
