### PR TITLE
Add Travis-CI continuous integration configuration

### PR DESCRIPTION
**Pull request by dstndstn**
Adds a .travis.yml file that instructs the Travis-CI.org service how to build the project.  This required a few additional configuration files (Gemfiles, _travis.yml).

As an added bonus, I fixed all the errors flagged by this Travis build.

### CODE REVIEW

**Comment by rgaiacs** [comment]
Hi @dstndstn. Thanks for all your good work on this. You aren't the only one looking to use Travis CI (or any other continuous integration solution for the lessons). I started working on a `.travis.yml` for all the lesson, see https://github.com/swcarpentry/lesson-example/pull/96, but I need feedback before roll it out. @swcarpentry/data-carpentry had also talked about it, see https://github.com/datacarpentry/R-ecology-lesson/issues/23 and https://github.com/datacarpentry/R-ecology-lesson/issues/154.

**Comment by dstndstn** [comment]
Indeed; thanks for the links.  Since I'm trying to complete the instructor checkout for SC and I've been preparing to teach the python lesson, I was looking in that list of issues, and the thinking in #319 of testing out Travis on one example lesson and then generalizing to lesson-example seemed reasonable.

How would you like to proceed -- do you want me to send a PR to lesson-example?  (I would also cherry-pick the fixes to the python lesson contents in this PR.)  Or do you want me to make comments on your swcarpentry/lesson-example#96 ?

**Comment by rgaiacs** [comment]
> How would you like to proceed

No problem to test on lessons. :-) Comments on my pull request are welcome to have the conversation in on place but I can cherry-pick your pull request later. :-)

**Comment by annefou** [comment]
@rgaiacs do you have any updates on the usage of continuous integration for Software Carpentry lessons?

**Comment by fmichonneau** [comment]
We'll start working on this after the bug BBQ.

**Comment by maxim-belkin** [comment]
Closing this as we now have Travis-CI working in our repo.
Thank you, @dstndstn!

**Pull request closed without merging**
