### PR TITLE
Update 02-loop.md

### PR DESCRIPTION
**Pull request by smakonin**
added a new outcome, this is my first check-in for carpentries.

Please delete the text below before submitting your contribution. 

---

Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  

Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact Kate Hertweck (k8hertweck@gmail.com).  

---

### CODE REVIEW

**Comment by maxim-belkin** [comment]
Hi @smakonin! Thank you for the PR! Is this part of instructor checkout?

**Comment by smakonin** [comment]
Yes, It is.

**Comment by ErinBecker** [comment]
This looks good to me! @maxim-belkin - can this be merged?

**Comment by maxim-belkin** [comment]
Erin, let's see what maintainers have to say :)

**Comment by maxim-belkin** [comment]
Thanks, @annefou! I will add my (less optimistic) comments later but wanted to hear what you and Mike think.

**Comment by maxim-belkin** [comment]
It would still require more work because it omits simple strings and loops as possible "collections" to be looped over.

**Comment by maxim-belkin** [comment]
@smakonin, I'm closing this PR for now but please feel free to re-open it if you feel we should discuss this more or when you get a chance to work on it based on my above comments.

Thank you!

**Pull request closed without merging**
