### PR TITLE
Removed blank lines from script, added comments

### LINKED ISSUE #68: Blank lines in Multiple Files lesson break indentation
In "Analyzing Data from Multiple Files"  [python-novice-inflammation/04-files.md line 52](https://github.com/swcarpentry/python-novice-inflammation/blob/gh-pages/04-files.md#L52)  there's a long script for looping through files and showing three plots. 

The script includes blank lines for readability.  The blanks mess up the indentation when the script is run in ipython.  The for loop prints three filenames,  then executes subsequent lines once.

### PR DESCRIPTION
**Pull request by janetriley**
Fixes #68 Blank lines in Multiple Files lesson break indentation

I added a few comments to break up the steps visually.

### CODE REVIEW

**Comment by janetriley** [comment]
Here's how it looks with comments.

pr 69-removed-blank-lines

**Comment by abostroem** [comment]
I'm with @tbekolay on the lack of blank lines being a readability issue. Has this been resolved by adding a note about magic pasting in the discussion.md file?

**Comment by abostroem** [comment]
I'd like to close this PR. Any objections?

**Comment by janetriley** [comment]
Sure, go ahead.
Janet
-- 
Janet Riley
jriley@janetriley.net
857-288-8428

On July 14, 2015 at 7:27:58 PM, Azalee Bostroem (notifications@github.com) wrote:

I'd like to close this PR. Any objections?

**Pull request closed without merging**
