### PR TITLE
Added second example to exponentiation

### PR DESCRIPTION
**Pull request by rhosking**

### CODE REVIEW

**Comment by kynan** [comment]
Not quite sure what this demonstrates?

**Comment by rhosking** [comment]
While only a small contribution, repetition helps, showing / typing another example could help generalise the idea.

I know I had to google the definition of exponentiation to double check I understood the notion.


On 13/02/2015, at 10:02 am, Florian Rathgeber <notifications@github.com<mailto:notifications@github.com>> wrote:


Not quite sure what this demonstrates?

**Comment by abostroem** [comment]
I'm not convinced this is necessary - other comments?

**Comment by timClicks** [comment]
Maybe we add another other example with `float`or possibly `decimal.Decimal` to show that `**` works with other date types?

**Comment by kynan** [comment]
It doesn't add anything as is, but using a different data type as suggested by @timClicks would be useful.

**Comment by gvwilson** [comment]
Thanks to @rhosking for the PR - I think exponentiation will be clear to our learners without the second example.

**Pull request closed without merging**
