### PR TITLE
Adding call stack section

### PR DESCRIPTION
**Pull request by c-martinez**
In the `Programming with R` lesson, the [`Creating functions` topic](https://swcarpentry.github.io/r-novice-inflammation/02-func-R.html) contains a section about call stack. The python lesson also has a `Creating functions` topic, which does not contain this section. It would be consistent to teach about call stacks in both languages. This pull request adds such section to the Python lesson.

### CODE REVIEW

**Comment by abostroem** [comment]
This adds a significant new section to the lessons. What part of the Python lesson would you remove in order to include this section?

**Comment by c-martinez** [comment]
I am not suggesting removing any part of the Python lesson. This new section does make the lesson longer, but it is just as long as [its R counterpart](https://swcarpentry.github.io/r-novice-inflammation/02-func-R.html). If adding this requires removing another section of the lesson, then perhaps a section of the R lesson should be removed as well?

**Comment by tbekolay** [comment]
Hi @c-martinez, we actually did have the mirrored content previously; it is still available in the [discussion page](http://swcarpentry.github.io/python-novice-inflammation/discussion.html). In the end, we found that most instructors teaching the lesson skipped this material, and so we chose to remove it from the main lessons, but left it in the discussion in case anyone still wanted to use it. I would be curious to know if those teaching R actually go over this content or skip it frequently as well...

**Comment by c-martinez** [comment]
Hi @tbekolay, ah -- good to know. So perhaps instead of this PR adding a section to the python lesson, I should send a new PR removing the section from the R lesson, to start the discussion ?

**Comment by tbekolay** [comment]
Sure, that sounds like a good way forward :)

**Comment by tbekolay** [comment]
Looks like https://github.com/swcarpentry/r-novice-inflammation/pull/158 has now been resolved, so closing, thanks @c-martinez!

**Pull request closed without merging**
