### PR TITLE
Update style to v9.5.0

### PR DESCRIPTION
**Pull request by rgaiacs**
No conflict is expected.

See more information at https://github.com/swcarpentry/styles/releases/tag/v9.5.0

### CODE REVIEW

**Comment by rgaiacs** [comment]
@maxim-belkin Feel free to discard this and merge styles directly.

**Comment by maxim-belkin** [comment]
@rgaiacs when I try this locally I get
```sh
$ make lesson-check
./aio.md: Unexpected metadata
configuration: "root" not set to "." in configuration
configuration: "root" not set to "." in configuration
configuration: "root" not set to "." in configuration
make: *** [lesson-check] Error 1
```

**Comment by rgaiacs** [comment]
@maxim-belkin copy defaults, see https://github.com/swcarpentry/styles/blob/gh-pages/bin/boilerplate/_config.yml#L62. Also, copy exclude, see https://github.com/swcarpentry/styles/blob/gh-pages/bin/boilerplate/_config.yml#L80.

I updated the instructions when you where trying.

**Comment by maxim-belkin** [comment]
Thank you @rgaiacs! Version 9.5.0 has been merged!

**Pull request closed without merging**
