### PR TITLE
Added challenge in topic 6 (functions).

### PR DESCRIPTION
**Pull request by chrismedrela**

### CODE REVIEW

**Comment by gvwilson** [comment]
Thanks - can you please mail Greg (gvwilson @ software-carpentry.org) so that we can connect your GitHub user ID with a real name?

**Comment by chrismedrela** [comment]
I've already mailed him. :) By the way, my real name is Christopher Medrela.

**Comment by gvwilson** [comment]
Hi Christopher,

My apologies, but I don't have a "Christopher Medrela" listed in any of 
our recent workshops. On the other hand, my record keeping is... well... 
let's say there's room for improvement.  Can you please mail me 
(gvwilson @ software-carpentry.org) and we'll sort it out?

Thanks,
Greg

**Comment by gvwilson** [comment]
This is a nice illustration, but we've avoided floating-point precision in this lesson - we're going to try to add it to the gapminder lesson.

**Pull request closed without merging**
