### PR TITLE
5.3 clean-up: Part 1

### PR DESCRIPTION
**Pull request by abostroem**
Clarifying text for section 01 - 05. I'll finish 06-09 tomorrow.

### CODE REVIEW

**Comment by tbekolay** [comment]
Aside from the inline comments, this looks good to me!

**Comment by abostroem** [comment]
I've addressed everything but the #73 (I've added a comment to that thread). @tbekolay Let me know how you feel about the new wording surrounding rows and columns.

**Comment by tbekolay** [comment]
New wording makes sense to me! I'll merge shortly.

**Comment by tbekolay** [comment]
Merged in ee3e9039c66344fb8a39c38e5d01b7a8c0ff4220!

**Pull request closed without merging**
