### PR TITLE
Moving towards compliance with template.

### PR DESCRIPTION
**Pull request by gvwilson**
1.  Moving material from `10-supplementary` into `discussion`.
2.  Adding styles.
3.  Making names consistent between links and files.

### CODE REVIEW

**Comment by kynan** [comment]
What's the rationale for moving supplementary material to discussion?

The rest is uncontroversial.

**Comment by tbekolay** [comment]
I'll second @kynan's comment; everything looks good to me, but I'm wondering if there's a precedent for putting additional material in the discussion section. I wonder if we should do what happened for the shell, and make a python-extras repo for this material instead?

**Comment by kynan** [comment]
I think the supplementary material as it is now doesn't warrant a dedicated repo. How do we intend this material to be used? Not for discussion I would think but rather as optional content that can be used if appropriate.

**Comment by abostroem** [comment]
I'll merge this later tonight. @gvwilson any final comments on the material moved to the discussion section?

**Comment by gvwilson** [comment]
No final thoughts from me.

**Pull request merged**
