### PR TITLE
Change 01-numpy.md. Commit again to try to fix repo errors

### PR DESCRIPTION
**Pull request by bjoyce3**
A small change in 01-numpy.md for finishing instructor training.

Blake Joyce
Instructor training: June 12th, University of Arizona

### CODE REVIEW

**Comment by abostroem** [comment]
@bjoyce3 Thank you for the rewording. There are a number of changes which are not really changes (I think the only change you are making is the very first change). Can you please update this PR to reflect only the intended change?

**Comment by bjoyce3** [comment]
I'd be happy to change my pull request. But I'm a little confused: Are you
asking me to redo the pull request and only change the wording of that one
section, or something else?

I was just adding some wording as a tiny little change, however when I pull
up the markdown file the spacing was off. I deleted the aberrant spacing,
and that is why the other changes showed up.

**Comment by abostroem** [comment]
The rewording is fine (you added a sentence correct?). The spacing changes make it harder to see what changes you made. Can you modify this pull request to only be the rewording. If you would like to change the spacing can you please submit that as a separate pull request?

**Comment by abostroem** [comment]
@bjoyce3 This looks like you deleted the whole file. Do you mind if I close this PR?

**Comment by bjoyce3** [comment]
Not at all. Thank you.

On August 16, 2015, at 16:18, Azalee Bostroem <notifications@github.com> wrote:

@bjoyce3 This looks like you deleted the whole file. Do you mind if I close this PR?

**Pull request closed without merging**
