### PR TITLE
Fix issue #329

### PR DESCRIPTION
**Pull request by dndln**
Referencing issue #329

### CODE REVIEW

**Comment by gvwilson** [comment]
Thanks very much - if this is for instructor training, can you please mail lessons@software-carpentry.org to let us know?  We don't have this GitHub ID in our records yet.
Thanks,
Greg

**Comment by dndln** [comment]
This isn't for instructor training (I don't know what that is!). 

I just read through the tutorial to learn, and noticed this as I went.

**Comment by valentina-s** [comment]
Thank you for working on fixing this exercise! It might be still confusing to people why the values should be positive and integer. I think if you rename it as something like get_total_count  and add a sentence in the beginning that these are counts, would make it more clear.

**Comment by dndln** [comment]
Updated!

**Comment by valentina-s** [comment]
Thanks!

**Pull request merged**
