### PR TITLE
Revision to Code Sample

### PR DESCRIPTION
**Pull request by mdsimpson42**
I tried to do a live code demo of this exercise during my Carpentries Instructor Training and noticed that this first piece of code will not run as it is currently written (as the variable "data" is not initialised before it is used). I have added the two additional lines of code necessary to make this code sample work. 

(This is part of my Instructor Training checkout process)

<details>
<summary><strong>Instructions</strong></summary>

Thanks for contributing! :heart:

If this contribution is for instructor training, please email the link to this contribution to
checkout@carpentries.org so we can record your progress. You've completed your contribution
step for instructor checkout by submitting this contribution!

Keep in mind that **lesson maintainers are volunteers** and it may take them some time to
respond to your contribution. Although not all contributions can be incorporated into the lesson
materials, we appreciate your time and effort to improve the curriculum. If you have any questions
about the lesson maintenance process or would like to volunteer your time as a contribution
reviewer, please contact The Carpentries Team at team@carpentries.org.

You may delete these instructions from your comment.

\- The Carpentries
</details>

### CODE REVIEW

**Review by ldko — APPROVED** [review]
Hi Mike,
The first 3 episodes of this lesson used to be one very long episode, and in splitting them up, the importing of `numpy` and setting of `data` is now in episode 2 and not redone in 3 for this code block. I think it makes sense to include the `import` and `data` initialization for those who jump in at episode 3 as you have done here. Thanks very much for submitting a change for this @mdsimpson42 !

**Comment by maxim-belkin** [comment]
Hi, @mdsimpson42. Thanks for the PR!

Good point. I agree that we need to update this (and, perhaps, other) episode(s) to make sure instructors load necessary librar(y/ies) and data if they're not continuing from the previous episode(s). I also like when episodes can be used as standalone modules and this change would make this episode independent. I wonder, though, if this can confuse learners who have imported the library and loaded the data in the previous episode. What do you and Lauren think about a callout or prereq box in the beginning of the episode reminding people to import library(-ies) and data again if they're not continuing from the previous episode?

**Comment by ldko** [comment]
Sure, I think it could be helpful to have a callout saying that if they are continuing from the previous episode, they don't need to `import` the library or set the `data` variable again, but that it is included for those who are not. I know this has come up as a question before in one of our Python workshops where someone asked if they needed to import again if they already had when the instructor imported more than once in a lesson.

**Comment by maxim-belkin** [comment]
Do you think you can find some time to update this PR to use a callout box instead, @mdsimpson42? The syntax for a callout box is:

```
> ## Title
>
> some text
{: .callout}
```

**Pull request closed without merging**
