### PR TITLE
Update 09-debugging.md: exercise time

### PR DESCRIPTION
**Pull request by davidbenncsiro**
5 or 10 minutes to complete exercises seems reasonable for this episode. The first exercise could take awhile so perhaps 10 minutes is closer to the mark.

### CODE REVIEW

**Comment by maxim-belkin** [comment]
Any interaction between learners takes time. I think 20 minutes would be a more realistic estimate for these two exercises.

**Comment by annefou** [comment]
I definitely agree with you @maxim-belkin 
I never managed to spend less than 20 mn on exercises!

**Comment by maxim-belkin** [comment]
Thank you, Anne.
David, could you please change exercise time to 20 minutes?

**Comment by maxim-belkin** [comment]
David, I went ahead and changed the time estimate to 20 minutes. I hope you don't mind.

**Comment by davidbenncsiro** [comment]
Thanks @maxim-belkin and apologies for the delay in getting to this. I've been a bit busy over the last several days. Happy for you to have made this change. There are other outstanding PRs that I will get too soon. Thanks again!

**Pull request merged**
