### PR TITLE
5.3 release edits part2

### PR DESCRIPTION
**Pull request by abostroem**
Updated lessons 06-09 (and a few references in 01) for 5.3 release. The most significant changes are reordering the lessons to put understanding errors before testing and removing references to dictionaries from the error lesson.

### CODE REVIEW

**Comment by tbekolay** [comment]
Made some comments inline! Other than those comments, all looks good to me.

Also, do you mind rebasing this branch to `gh-pages` when you update this PR? I've merged in #80, which this branch is based on, so if you don't rebase then there'll be some difficult conflicts. Also, this is going to conflict with #79; which should we merge first? If you'd prefer this merged first, I can redo #79, just let me know.

**Comment by abostroem** [comment]
Why don't you merge #79 first, then I can (try) to rebase and tidy everything up on this branch before merging it in

**Comment by abostroem** [comment]
@tbekolay I think I managed to rebase this, address your comments, regenerate html and push it. One thing I realized in the process if that you may have put defensive first and then debugging second and I switched the order. This is unintentional and if you think it should be the other way feel free to switch it back. I also created a call out in the 10-cmdline lesson to tell people that the $ means shell. Let me know how you like that. Finally, we are still getting a few errors from make check, but I'm not sure how to fix them.

**Comment by tbekolay** [comment]
Callout looks good to me! I'll fix the file order in the merge. And I'll check the `make check` output... I think some of it is erroneous (false positives) but I'll check to make sure.

**Comment by tbekolay** [comment]
Merged in 89525304ede0! The `make check` results are all warnings, except for a FIXME in the discussion (not worth fixing right now, for sure) and a missing section in `index.md`. I'll make a PR for that shortly.

**Pull request closed without merging**
