### PR TITLE
refactor python-overlapping-ranges.svg source, remove odg file (towards #494)

### PR DESCRIPTION
**Pull request by edbennett**
ran this SVG file through a minifier, then went and hand-tuned the result. in principle it could be simplified slightly further by removing the view box, but that then basically needs redrawing everything in the new co-ordinate system so it still lines up. Still around 97% smaller than the old SVG. Removed the ODG file because it doesn't make sense to edit and export any more.

### CODE REVIEW

**Comment by maxim-belkin** [comment]
Amazing! Thanks, Ed!
I'll see if I can quickly change the viewbox issue (as having font size of 388 is a bit weird).

**Comment by edbennett** [comment]
As a PS, I also changed the hyphens to minus signs, as I'm pedantic about that kind of thing.

**Comment by edbennett** [comment]
Thanks for fixing that Maxim; looks good to me.

**Comment by maxim-belkin** [comment]
Thank you, Ed, very much for your contribution to the lesson! 🎉

**Pull request merged**
