### PR TITLE
06-func.md: simplify function composition example

### PR DESCRIPTION
**Pull request by dstndstn**
build fahrenheit-to-kelvin out of fahrenheit-to-celsius and celsius-to-kelvin

This also updates the figure illustrating the parts of a function definition.

This is for issue #366

### CODE REVIEW

**Comment by valentina-s** [comment]
I like this simplification. I have to admit that I think I have taught it this way (without realizing) since it is more natural: as a European in US I always have to convert from F to C first... I will let @tbekolay decide whether it is worth updating.

**Comment by maxim-belkin** [comment]
I like this change.
@dstndstn if you could rebase this PR on top of the current `gh-pages` branch that would be very much appreciated.

```
git rebase gh-pages composing-functions
```

**Comment by maxim-belkin** [comment]
Let me, however, check if we can clean up SVG code first

**Comment by maxim-belkin** [comment]
OK, let's work on SVG figures in a different PR.
Thanks, @dstndstn, for improving to the lesson!

**Pull request closed without merging**
