### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by katrinleinweber**
See diff ;-)

### CODE REVIEW

**Comment by maxim-belkin** [comment]
Thank you!

**Comment by katrinleinweber** [comment]
You're welcome. Did you cherry-pick to avoid another merge commit for such a small change? I imagin that were some more work steps than clicking merge ;-)

**Comment by maxim-belkin** [comment]
I didn't cherry-pick but I do make a few more steps:

```sh
git pull origin pull/<PR-num>/head  # pull the PR to currently-active branch
git commit -s --amend
git push
```
`-s`: to add info who takes the responsibility for this commit because there are several maintainers
`--amend`: to add `Closes ....#` to automatically close the PR (and related issues, if any) and fix the commit message to adhere to `FILE: change` format

**Comment by katrinleinweber** [comment]
Good idea! `r-novice-inflammation` will soon have another maintainer, who I could try this with. Thanks for the instructions :-)

**Pull request closed without merging**
