### PR TITLE
Merging new styles and documentation

### PR DESCRIPTION
**Pull request by gvwilson**
This PR brings in all of the 2016-06 template, along with documentation on building lessons.

### CODE REVIEW

**Comment by valentina-s** [comment]
Thanks Greg for converting the lesson! One remark I have is regarding the times allocated to the lessons: as of now I think the schedule is overly ambitious. Here we usually cover material up to functions including command line programs in a full day. I think this varies widely on the students, instructor, number of exercises... Maybe we should explicitly state somewhere in the lesson that these times can be variable: I don't want instructors to start rushing for materials just because we fixed a lesson to 20 min. That I think applies to all lessons.

There are still a few typos and inconsistencies which were left after the merges, so I put a list of all of them in one issue #287 (including some of my ideas for improvement). I could fix the simple stuff after the merge and leave more major modifications for the future.

**Comment by gvwilson** [comment]
Hi Valentina,

Pull requests to make the times more realistic are very welcome - what's 
in there now is mostly out-of-date guesswork.  And yes, there should be 
a note somewhere that times are provisional and advisory - what and 
where do you think best?

Cheers,
Greg

**Comment by valentina-s** [comment]
We could add a footnote to the title Schedule, and below the actual schedule state something like

The suggested schedule will vary depending on topics and exercises covered.

?

**Comment by gvwilson** [comment]
Sure - file a PR in the lesson-example repo and I'll fold it into the docs?

**Comment by valentina-s** [comment]
Filed as #295 within this lesson. Also submitted a PR to the lesson-example #44.

**Comment by gvwilson** [comment]
Merged.

**Pull request merged**
