### PR TITLE
setup.md: add section headers, rewrite, and simplify

### PR DESCRIPTION
**Pull request by maxim-belkin**
* Add section headers

This should help workshop instructors if attendees have any troubles
during preparation. They can easily refer to a specific section.

* Reorganize

The first option to launch Python interpreter is now `python` command.
Remove duplicate references to Unix shell.

### CODE REVIEW

**Comment by annefou** [comment]
I would not have Optional for jupyter notebook. It does not really correspond to what is taught. I mean jupyter notebook are vastly used for teaching python.

**Comment by maxim-belkin** [comment]
> I would not have Optional for jupyter notebook. It does not really correspond to what is taught. I mean jupyter notebook are vastly used for teaching python.

OK. Thank you!

**Comment by maxim-belkin** [comment]
I'd like to get a few more comments on this PR before merging it... so let's keep it open for some time.

**Comment by maxim-belkin** [comment]
I just realized that the first two titles describe some actions (**Get** the data, **Launch** the interpreter). It would be better if the third title follows the same rules.

**Pull request closed without merging**
