### PR TITLE
link PNGs instead of SVGs (closes #270 and #271)

### LINKED ISSUE #270: overlap in figure: Operation Across Axes
There is an overlapping in the figure "Operation Across Axes" of the section 01-Numpy.

### PR DESCRIPTION
**Pull request by btel**
It replaces links to SVG files with links with respective PNGs. This solves the problem with differences of rendering of SVGs on different platforms and browsers (mainly related to fonts - see #270 and #271).

### CODE REVIEW

**Comment by tbekolay** [comment]
Could you remove the changes to the HTML files in this PR? Right now there's a ton of noise for a small change in the markdown files. Let me know if you want help with this!

**Comment by gvwilson** [comment]
Hm - we generally prefer SVG to Markdown because SVG rescales better on 
small screens, but on the other hand, if the fonts aren't rendering...

**Comment by btel** [comment]
@tbekolay sorry for that. I fixed the PR.

@gvwilson I agree it would be better to link SVGs instead of PNGs. The problem appears mostly in FF. On Chrome there are only minor formatting issues (the monospace font does not render).

**Comment by tbekolay** [comment]
> sorry for that

No problem :) I'm 👍  on this PR but will wait for at least one other :+1: before merging (@gvwilson?)

**Comment by gvwilson** [comment]
Go ahead - we'll figure it out.

**Comment by btel** [comment]
BTW An alternative solution would be to replace text by paths. This way we keep SVG format, but we loose the possibility to edit texts.

**Comment by tbekolay** [comment]
Thanks @btel! PS: I'm a big fan of svg_utils, used it for a lot of figures :)

**Pull request merged**
