### PR TITLE
08-defensive.md: use correct dash character

### PR DESCRIPTION
**Pull request by cleary3**
Use an en dash (–) instead of a figure dash (-) when specifying a numeric range.

Please delete the text below before submitting your contribution.

### CODE REVIEW

**Comment by rgaiacs** [comment]
Hi @cleary3, can you send a pull request to https://github.com/swcarpentry/lesson-example with a change to http://swcarpentry.github.io/lesson-example/06-style-guide/index.html, you need to edit https://github.com/swcarpentry/lesson-example/blob/gh-pages/_episodes/06-style-guide.md, that add the use of figure dash, en dash and em dash? Many people aren't familiar with the different use cases and neither on how they can insert those characters. Thanks in advance.

**Comment by cleary3** [comment]
OK, I think I've done it:
https://github.com/swcarpentry/lesson-example/pull/181

**Comment by maxim-belkin** [comment]
How about `10-20%` on the line above?

**Comment by cleary3** [comment]
Yep, that's in pull request 480: https://github.com/swcarpentry/python-novice-inflammation/pull/480

**Comment by maxim-belkin** [comment]
I have mixed feelings about this and the other PR... Shouldn't we use `&mdash;` or `&#8212;` for '&mdash;' and `&ndash;` or `&#8211;` for '&ndash;'?

**Comment by cleary3** [comment]
That's fine with me. However, my pull request sparked a larger conversation about whether it's even worthwhile to use em- and en-dashes in the Software Carpentry lessons. (The fear being that they'd be applied inconsistently and be distracting to the learners going through the lessons.)

**Comment by maxim-belkin** [comment]
I'm all for using them em- and en-dashes. I just question what is the right way of doing that in Markdown.

**Comment by cleary3** [comment]
Well, I'd vote for readability and go with `&mdash;` and `&ndash;`.

**Comment by annefou** [comment]
I close this PR. We may change it again once a conclusion about the usage of dash (beyond this PR) is reached.

**Comment by maxim-belkin** [comment]
@annefou you merged it, you didn't close it :) that's fine though

**Pull request merged**
