### PR TITLE
Renamed modules with dashes to underscores

### PR DESCRIPTION
**Pull request by zonca**
Cannot import module with dashes.
The lesson text uses underscores.

### CODE REVIEW

**Comment by tbekolay** [comment]
We actually have a bunch of files in `code` that have dashes; would you mind changing them all?

**Comment by zonca** [comment]
all the others are scripts, so there is no issue if they have dashes. I recommend to leave dashes on those so we don't have to change the lesson material.

**Comment by tbekolay** [comment]
Fair!

**Comment by tbekolay** [comment]
Thanks for your contribution @zonca!

**Pull request merged**
