### PR TITLE
setup.md: reorganize and update

### PR DESCRIPTION
**Pull request by maxim-belkin**
Updating the setup page:

- added "Overview" section
- reorder items in the "Launch Python Interpreter" section (as discussed in the last maintainers' meeting)
- moved instructions from the "navigate to the data folder" to the previous section

I pushed these changes to the `gh-pages` branch of my fork, so they can be previewed here:
https://maxim-belkin.github.io/python-novice-inflammation/setup/index.html

### CODE REVIEW

**Comment by maxim-belkin** [comment]
we can later add options to use JupyterLab and Spyder

**Comment by maxim-belkin** [comment]
Thanks, Lauren. Could you please have a look at some minor changes that I made after I submitted the PR (https://github.com/swcarpentry/python-novice-inflammation/pull/778/commits/30e12162757040777af28de7c2f6fe0dcaad45fd)?

**Comment by ldko** [comment]
The changes in the new commit look fine to me.

**Comment by maxim-belkin** [comment]
Thank you, Lauren!

**Pull request merged**
