### PR TITLE
Add motivation slides

### PR DESCRIPTION
**Pull request by tbekolay**
This is a starting point for making this repository pass the tests run with `make unittests`. I fixed the first few tests that were failing; things like missing `motivation.md` etc.

However, this remains a WIP because a lot of the logger messages from the test suite are too confusing to fix. The test suite seems to be based on matching content to some templates that are defined in the tests; however, when a test fails, it spits out information from the template rather than the content that isn't matching the test, making it very difficult to figure out what's actually wrong. So, before moving on with this branch, I'll work on the test suite in the [lesson_template](https://github.com/swcarpentry/lesson-template) repo.

Also note that this is based on the `update-core` branch from #26 since it has the most up-to-date tests.

### CODE REVIEW

**Comment by abought** [comment]
I'm totally open to cleaning up the unit tests on the validator. (Including better separation of unit, functional, and integration tests- some of the tests depend on example files not found on the core branch) Send me a note with any questions/ requests.

But since you mention uncertainty about the error messages: the unit tests are not a way to check a specific lesson repo; they are for internal use to ensure that the validator itself (as it exists in lesson-template) is working correctly. If you are trying to find out what files in your actual lesson have problems, try `python tools/check.py <filename>`

**Comment by tbekolay** [comment]
Oh! That makes a lot more sense, thanks for the clarification @abought.

**Comment by r-gaia-cs** [comment]
@tbekolay This looks good to merge.

**Comment by vahtras** [comment]
I started looking at this as well before seeing this PR. My confusion was also that I thought "make unittest" was something that applied to the lesson rather than the internal workings of the validator. Wouldn't it be better to have a "make check" that calls tools/check.py instead?

**Comment by gvwilson** [comment]
The name change makes sense to me - thoughts from others?

**Comment by r-gaia-cs** [comment]
There is a pull request to fix the name confusion: https://github.com/swcarpentry/lesson-template/pull/164.

@gvwilson The pull request looks good to me. Could you check that the default `make` output is OK, https://github.com/swcarpentry/lesson-template/pull/164#issuecomment-73826041?

**Comment by kynan** [comment]
Looks good. One thing to consider @tbekolay: Load bootstrap from CDN rather than include it in the repo.

**Comment by gvwilson** [comment]
Does this one need to be rebased on top of recent changes?

**Comment by tbekolay** [comment]
This was based on #26, but it seems that the `lesson-template/core` branch was merged into `gh-pages`, so it would need to be rebased, yes. I haven't run this with the actual check script on this branch, so I'm not sure if this is ready to merge (but if other people have run it, then feel free!)

**Comment by kynan** [comment]
Thoughts on loading bootstrap from CDN versus including the files @tbekolay @gvwilson?

**Comment by tbekolay** [comment]
@kynan I'd be a +1, but I think that's orthogonal to the purpose of this PR; some bootstrap stuff is included in here only because this branch includes some commits from [swcarpentry/lesson-template](https://github.com/swcarpentry/lesson-template) I'd recommend making an issue in that repo to discuss loading bootstrap from a CDN.

**Comment by kynan** [comment]
@tbekolay OK, hadn't realised that. Will create an issue for it.

What's the policy for rebasing? Do we force push?

**Comment by kynan** [comment]
Issue filed: swcarpentry/lesson-template#172

**Comment by gvwilson** [comment]
@tbekolay has this one gone stale?

**Comment by kynan** [comment]
Rebased! @tbekolay I left out the instructors stub, since @gvwilson had started on this in the meantime. Thoughts?

**Comment by gvwilson** [comment]
Is this one still relevant?

**Comment by kynan** [comment]
Rebased again. @tbekolay is this good to go?

**Comment by tbekolay** [comment]
I updated the title to be more factual; this PR mostly adds motivation slides, and also fixes a bit of the `index.md` formatting. This is good to go; feel free to merge and regenerate HTML @kynan!

**Comment by kynan** [comment]
Regenerated HTML in 29c1ff8.

**Pull request merged**
