### PR TITLE
Episode 7: Add `None` to "What is Truth?" challenge

### PR DESCRIPTION
**Pull request by vinisalazar**
Related to issue #358.

### CODE REVIEW

**Comment by ldko** [comment]
Note: up through episode 7, `None` has not been introduced in the lesson, so including it in the challenge is problematic.

**Comment by vinisalazar** [comment]
Hi, thank you for the comments.

@maxim-belkin I am aware that Python is case-sensitive. All other statements in the challenge are in lower case, I simply wanted to maintain consistency.

@ldko that is indeed a problem. I see now that `None` is only introduced in Episode 8.

My apologies, I will close this PR and refrain from making such changes without proper justification.

Best,
V

**Comment by ldko** [comment]
@vinisalazar thanks for taking the time to submit this suggestion. `None` evaluating to `False` is one of those things that will come in handy for people who continue using Python to know at some point. Unfortunately, there are so many useful things like this, we have to leave a lot of them out keeping in mind that these materials are designed to be used in a workshop format where the lesson is generally covered in 6 hours. Some of the things we leave out are mildly painful, but in the context of the materials, we do it. :) Thanks for all your contributions this past week!

**Comment by vinisalazar** [comment]
@ldko I understand and agree with you. As for the contributions, I'm happy to help! :)

Best,
V

**Pull request closed without merging**
