### PR TITLE
episode 05 - another way to get start of string

### PR DESCRIPTION
**Pull request by tj-sun**
Another way to compare the start of the string using list slicing.

This doesn't introduce any new conceptual burden as learners have already seen list slicing earlier.
I also think it's a more commonly used way to compare substrings, and also helps reinforces the concept of list slicing, which is very useful.

### CODE REVIEW

**Comment by maxim-belkin** [comment]
Thanks, @tj-sun. While this does not introduce any "new" material, this does break the flow of the explanation there (the sentence that starts with "But..." no longer refers to the statement that precedes it but to the one before it...).

**Comment by tj-sun** [comment]
Got it - that's a good point, we certainly shouldn't digress from the logic flow. Probably better that the instructor just brings this up when he/she sees fit.

Feel free to close this.

**Comment by maxim-belkin** [comment]
How about, we start with this comparison and then mention `startswith` ?
CC @annefou

**Comment by annefou** [comment]
@maxim-belkin I definitely like your last suggestion; and make it clear to the instructor that this can be raised if it fits the attendance (depending on your audience and questions raised).

**Pull request closed without merging**
