### PR TITLE
Adds table of lesson episodes to README [#495]

### PR DESCRIPTION
**Pull request by SamStudio8**
Attempting to address some outstanding issues documented in #495.

* Introduces SWC
* Adds table of episodes
* Adds LICENSE information

### CODE REVIEW

**Comment by rgaiacs** [comment]
Hi @SamStudio8. Thanks for the pull request. I understand why is good to have the table of contents in the README but as it might broke and get out of date I'm against it. The GitHub Pages of the lesson has the table of content.

**Comment by SamStudio8** [comment]
Hi @rgaiacs, that's ok! It was on the list of suggestions from #495. Let me know if the other changes are of use to you and I can fix the request.

**Comment by maxim-belkin** [comment]
Thank you, @SamStudio8, for the PR, and thank you, Raniere, for the feedback.

I'm not worried that TOC will get out of date as the lesson contents is pretty stable. This does not mean, however, that we don't have to discuss it (its purpose, contents, usefulness, etc.).

There is no need to change AUTHORS file (it will be updated with `update-copyright` Python module before the next release). 

Please move non TOC-related changes to other PRs. You might want to consult with our "wiki", specifically these pages:

1. https://github.com/swcarpentry/python-novice-inflammation/wiki/Fixing-a-PR-created-from-the-gh-pages-branch
2. https://github.com/swcarpentry/python-novice-inflammation/wiki/Splitting-(Breaking-down)-Pull-Requests

You may, of course, also have a look at our [general contributing guidelines](https://github.com/swcarpentry/python-novice-inflammation/blob/gh-pages/CONTRIBUTING.md#using-github).

Regarding lesson intro - please don't introduce SWC in there (at least for now). I think intro has to be lesson-specific. I think it makes sense to discuss this among the broader group of The Carpentries' maintainers.

**Comment by maxim-belkin** [comment]
Thanks, @SamStudio8. This split is exactly what I wanted.

**Pull request closed without merging**
