### PR TITLE
reference.md: add definition of a mutable type

### PR DESCRIPTION
**Pull request by dlm**
Use definition provided by @NickleDave

### CODE REVIEW

**Comment by dlm** [comment]
Addresses #416

**Comment by NickleDave** [comment]
Thank you @dlm for taking care of this, I kept meaning to get back to it but obviously hadn't

**Comment by maxim-belkin** [comment]
Cool! Thanks @dlm (and @NickleDave :)).

**Comment by dlm** [comment]
No prob!

**Pull request closed without merging**
