### PR TITLE
Added setup instructions for Windows with no Unix shell

### PR DESCRIPTION
**Pull request by tiagopereira**
To address https://github.com/swcarpentry/python-novice-inflammation/issues/436, added a couple of lines to the setup instructions so that Windows users with no Unix shell installed can instead run Python or Jupyter from `cmd`.

### CODE REVIEW

**Comment by valentina-s** [comment]
Thanks for the suggestion! This can be helpful. I believe  the `cd` commands from above (navigating to the data directory) will not work in the Windows prompt. Could you add a version of the command compatible with windows? Do you think there is any benefit to use the anaconda prompt vs command prompt?

**Comment by tiagopereira** [comment]
Hi @valentina-s thank you for noting that the `cd` commands were not working. I've made a slight change to enable access to the Desktop folder in Windows with `cd` from `cmd`. It should work, but please let me know if this works (I don't have a Windows machine to test).

**Comment by valentina-s** [comment]
@tiagopereira Thank you for the addition. I am pretty sure you do not need the /d (that seems to be needed if you need to switch between drives, which most probably they will not).

**Comment by tiagopereira** [comment]
You're right, `/d` is not necessary, but it will make it work in any circumstance.

**Pull request merged**
