### PR TITLE
Added a few sentences to help clarify the meaning of the data set.

### PR DESCRIPTION
**Pull request by wirawan0**
I want to help clarify the meaning of the numbers in the dataset. For a long time, whenever I read this lesson, I got hung up with not understanding what the numbers mean. Although the sentence prior to the illustrative dataset says it: "data sets of their daily inflammation", I did not get what those numbers mean. I added these two sentences to help clarify.

Wirawan

### CODE REVIEW

**Comment by maxim-belkin** [comment]
Seems reasonable. Thank you, @wirawan0. Could you please wrap lines to 100-characters (you can copy the text in the quote below)?

> Each number represents the number of inflammation bouts that a particular patient experienced on a 
given day. For example, value "6" at row 3 column 7 of the data set above means that the third 
patient was experiencing inflammation six times on the seventh day of the clinical study.

**Comment by annefou** [comment]
It would be nice to be able to close this PR.  I think I added what was requested to accept it. @maxim-belkin  let us know if it is ok. Thanks.

**Comment by maxim-belkin** [comment]
Look good to me! Thank you, Anne!

**Comment by wirawan0** [comment]
Thanks @annefou for doing what I ought to be doing. Thanks @maxim-belkin for accepting the PR.

**Pull request merged**
