### PR TITLE
Feature/image alt text

### PR DESCRIPTION
**Pull request by blankdots**
Aims to solve some of  https://github.com/swcarpentry/python-novice-inflammation/issues/781

Followed the recommendations at: https://webaim.org/techniques/alttext/#basics trying to be as specific as possible for the content and the function.

The zero index `python-zero-index.png` is the one that i am most unsure about, as it is quite difficult to detail what is happening there.

- [x] `01-intro.md > Variables as Sticky Notes`
- [x] `01-intro.md > Creating Another Variable`
- [x] `01-intro.md > Updating a Variable`
- [x] `02-numpy.md > Zero Index`
- [x] `02-numpy.md > Operations Across Axes`
- [x] `07-cond.md > Executing a Conditional`
- [x] `08-func.md > The Blueprint for a Python Function`

I will do the others in a different PR as figuring out how to properly explain the plots require more time.

### CODE REVIEW

**Comment by ldko** [comment]
@maxim-belkin were you intending that each image's `alt` text be submitted as a separate PR?

**Comment by maxim-belkin** [comment]
> @maxim-belkin were you intending that each image's `alt` text be submitted as a separate PR?

Ideally, yes. I prefer unrelated changes to be in different PRs solely because it allows us to discuss these changes in greater detail without losing track of each discussion.

**Comment by blankdots** [comment]
@maxim-belkin @ldko ok I will close this PR and do new ones for each `alt`.

**Comment by blankdots** [comment]
Closing as suggested to individual PRs for each `alt` text:  #792  #793  #794  #795  #796 #797 #798

**Pull request closed without merging**
