### PR TITLE
Update 03-lists.md

### PR DESCRIPTION
**Pull request by davidbenncsiro**
0 minutes for exercises seems a bit optimistic. :)

I'm not sure of the right number here but perhaps 10 mins?

I've just noticed that most episodes except for the first only show teaching time. Is the assumption that exercises are included in that time?

### CODE REVIEW

**Comment by maxim-belkin** [comment]
> 0 minutes for exercises seems a bit optimistic. :)
>...
> I've just noticed that most episodes except for the first only show teaching time. Is the assumption that exercises are included in that time?

"0 minutes for exercises" is our legacy. We do need to update all episode to list more or less accurate time for exercises.

10 minutes for 4 exercises is definitely more realistic though is still optimistic (at least when I teach I spend more than 10 minutes). I think 3-5 mins per exercise, 12-20 min total, is more realistic. Perhaps, 15 minutes?

**Comment by annefou** [comment]
I agree 15-20 mn is indeed more realistic.

**Comment by maxim-belkin** [comment]
What do you think, @davidbenncsiro? Would you mind updating the estimate to 15 or 20 minutes?

**Comment by davidbenncsiro** [comment]
Thanks @annefou and @maxim-belkin, I've updated it to 15 mins.

I suppose at some point, the same question can be answered for the other episodes. Shall I create a PR for those as well?

**Comment by maxim-belkin** [comment]
> Thanks @annefou and @maxim-belkin, I've updated it to 15 mins.

Thank you, David!

> I suppose at some point, the same question can be answered for the other episodes. Shall I create a PR for those as well?

Yes, please! And thanks again!

**Pull request merged**
