### PR TITLE
Update loop variable names in code file

### PR DESCRIPTION
**Pull request by sparce**
Split from PR #734

### CODE REVIEW

**Comment by maxim-belkin** [comment]
Could you please swap all `data.***` with `numpy.***(data,` ? This is what we currently have in the episode.

**Comment by maxim-belkin** [comment]
Thank you for contributing to the lesson, Stephen!
16 pull requests! Fantastic work! 🎉

**Comment by sparce** [comment]
Didn't realise quite what I was getting myself in for! 😁 Thanks for walking me through everything.

**Comment by ldko** [comment]
Thanks so much @sparce and @maxim-belkin for going through all of these files to handle the loop variable issue. It is much appreciated!

**Pull request merged**
