### PR TITLE
Update 07-cond.md

### PR DESCRIPTION
**Pull request by gerdos**
Added two challenge exercises that my students usually find fun to think about.

<details>
<summary><strong>Instructions</strong></summary>

Thanks for contributing! :heart:

If this contribution is for instructor training, please email the link to this contribution to
checkout@carpentries.org so we can record your progress. You've completed your contribution
step for instructor checkout by submitting this contribution!

Keep in mind that **lesson maintainers are volunteers** and it may take them some time to
respond to your contribution. Although not all contributions can be incorporated into the lesson
materials, we appreciate your time and effort to improve the curriculum. If you have any questions
about the lesson maintenance process or would like to volunteer your time as a contribution
reviewer, please contact The Carpentries Team at team@carpentries.org.

You may delete these instructions from your comment.

\- The Carpentries
</details>

### CODE REVIEW

**Comment by maxim-belkin** [comment]
Very interesting challenges, @gerdos!

What do you think, @ldko and @annefou? I see a couple of grammatical and stylistic issues... but other than that -- I like both challenges.

**Comment by annefou** [comment]
Ineed very interesting. I like the first challenge. For the second part, I wonder if it is worth to have is as a challenge (I don't think this is something a novice can easily find the solution); maybe rather have it as a callout.

**Comment by ldko** [comment]
I would be ok with including either or both challenges. Regarding what @annefou says about the second challenge, I wonder if modifying it to be a multiple choice type of question that has multiple correct answers and explanations in the solution would make it more suitable.

**Comment by annefou** [comment]
> I would be ok with including either or both challenges. Regarding what @annefou says about the second challenge, I wonder if modifying it to be a multiple choice type of question that has multiple correct answers and explanations in the solution would make it more suitable.

@ldko I like your suggestion!

**Pull request closed without merging**
