### PR TITLE
Small changes from review

### PR DESCRIPTION
**Pull request by QuLogic**
After reviewing the lesson for instructor training, I've put together several small changes that fix minor issues like typos, etc..

### CODE REVIEW

**Comment by QuLogic** [comment]
It looks like I have fixed #217 and #218 in here too.

**Comment by iglpdc** [comment]
Great! +1 (maybe merging first #217 and #218)

**Comment by tbekolay** [comment]
This all looks great! I am going to skip the changes to `python3` in 1366e046e8d0048c760e744e4bbba3bdf3803a17 because 1) this breaks things for me because I use a virtual environment and 2) eventually `python` should reference `python3` and the special case will be `python2`.

**Comment by QuLogic** [comment]
> 1) this breaks things for me because I use a virtual environment

Hmm, sounds like another thing broken with `virtualenv`. Conda and pyvenv seem to do this correctly?

> 2) eventually python should reference python3 and the special case will be python2.

Unfortunately, PEP0394 doesn't have much of a timeline for it, _but_ it does suggest writing a cross-compatible script if using the `python` reference, so everything should be working right now.

**Comment by tbekolay** [comment]
> Hmm, sounds like another thing broken with virtualenv. Conda and pyvenv seem to do this correctly?

Yeah, this is mostly an issue with my setup. I'm using a python2 virtualenv; were I using a python3 virtualenv it would work fine. Another issue that I should have mentioned is that the `Makefile` is shared across all lesson repositories, so changing it might make it more difficult to pull in changes from [lesson-template](https://github.com/swcarpentry/lesson-template/blob/gh-pages/Makefile) in the future.

**Pull request merged**
