### PR TITLE
Update 08-supplementary.md

### PR DESCRIPTION
**Pull request by raffademichelis**

### CODE REVIEW

**Comment by abostroem** [comment]
Can someone who has taught this lesson comment on this PR?

**Comment by kynan** [comment]
imho this comment is too unspecific to add anything substantial.

**Comment by gvwilson** [comment]
How about `RGB codes for commonly-used colors can be found at [many](link) [web](link) [sites](link), and there are [many](link) [web-based](link) [tools](link) to create them.`  (Learners find it frustrating to be told that something exists, but not told where to find it.)

**Comment by jiffyclub** [comment]
Related to this, ipythonblocks has an `embed_colorpicker` function that embeds an `iframe` with http://www.colorpicker.com/ in the Notebook. When I've [taught with ipythonblocks](https://github.com/jiffyclub/boot-camp-template/blob/master/python/ipythonblocks/instructor_notes.md#color) (not this specific lesson, though), I've led with a discussion of RGB colors that includes `show_color` and `embed_colorpicker`.

screenshot 2015-02-23 10 10 09

**Comment by jiffyclub** [comment]
And if you are going to link to anything, I would link to this: http://en.wikipedia.org/wiki/Web_colors#X11_color_names. Those names and colors match what's in the `ipythonblocks.colors` object.

**Comment by tbekolay** [comment]
I think this is a helpful paragraph to include. @raffademichelis, how do you feel about adding the text that @gvwilson suggested above? You can use the links that @jiffyclub recommended, or others that you think are helpful. I'm happy to merge once the feedback's incorporated.

**Comment by tbekolay** [comment]
Since this PR hasn't progressed in over a year, I'm going to close it. I'm adding the `revise-and-resubmit` label because this PR would be welcome in this lesson, but not in its current state. If the PR is updated then feel free to reopen it! Or submit a new PR.

**Pull request closed without merging**
