### PR TITLE
Updated Python Loop Lesson to Address Indexing

### PR DESCRIPTION
**Pull request by rspavel**
Previous version of python loop lesson introduced ambiguity in how to
index into an array/list/string in Python. Updated to make it clear that
Python indexes from zero so as to not introduce this ambiguity

### CODE REVIEW

**Comment by valentina-s** [comment]
Thank you for the suggestion @rspavel. Since the numbers in the diagram refer to the loop cycle(not the index) I think it is correct for them to be 1-6.

**Comment by annefou** [comment]
@valentina-s I think you are correct too. Shall we close this PR?

**Comment by maxim-belkin** [comment]
@rspavel is this PR part of your instructor checkout process?

**Comment by maxim-belkin** [comment]
By the way, I concur with @valentina-s and @annefou.

**Comment by maxim-belkin** [comment]
I think the point here is that the **first** **\*index\*** in an array is **zero**  but if you want to number iterations of a **\*loop\*** you would still start from **one** (first iteration, second iteration, ...)

I think a PR to make the word "loop" bold would be reasonable. I also think it would be better to say `iteration of a loop` rather than just a `loop`.

Thank you, @rspavel!

**Pull request closed without merging**
