### PR TITLE
setup.md: link to Git Bash

### PR DESCRIPTION
**Pull request by cleary3**
Add a link for 'git bash.' Up to this point, 'git bash' has not been mentioned in the Programming with Python lesson material. Without the link, it's unclear whether 'git bash' is a product or a typo.

### CODE REVIEW

**Comment by rgaiacs** [comment]
Not that type `python` in Git Bash will probably return

~~~
command not found: python
~~~

You probably want to point Windows users to the Anaconda prompt.

**Comment by maxim-belkin** [comment]
@cleary3 could you please rebase this PR and change `git bash` to `Git Bash`?

**Comment by cleary3** [comment]
My git novice threads are showing through. I believed I've rebased my pull request and update it, as requested.

**Comment by maxim-belkin** [comment]
not a problem. give me a few minutes - I'll either clean this up myself or post instructions how to fix things

**Comment by maxim-belkin** [comment]
So, Git Bash is first mentioned a few lines above (line 28) so we actually have to add the link there.
Let's fix it the hard way:
```
$ git checkout patch-1
$ git reset --hard origin/gh-pages
### edit setup.md to add the link here ###
$ git add -u 
$ git commit ...
```

**Comment by maxim-belkin** [comment]
I've updated `setup.md` and I believe this issue is now resolved.
Thank you for your contribution anyway, @cleary3!

**Pull request closed without merging**
