### PR TITLE
Adding instructions to starting ipython.

### PR DESCRIPTION
**Pull request by djw8605**
This fixes issue #136.

### CODE REVIEW

**Comment by tbekolay** [comment]
While it is true that many instructors teach the lesson with the IPython / Jupyter notebook, the lesson materials are designed to be used from any environment (e.g., a bare Python interpreter). So, while we would definitely like to add in some text about how to start the notebook, it would have to be accompanied by text for other ways of starting up Python (specifically, starting a Python interpreter from the shell). If you don't mind adding that in that would be great; otherwise, I'll add in that text in another PR.

Additionally, people installing Anaconda from scratch at the moment are instructed to run `jupyter notebook` instead of `ipython notebook`. Both should be included as we can't guarantee what versions learners will have.

**Comment by djw8605** [comment]
Both `jupyter notebook` and `ipython notebook` work on a new installation of Anaconda.  I wonder if this will be kept for a while?  Anyways, it works right now, and starts the same service.  A consistent command across versions like `ipython notebook` is probably the ideal way to go, for now.

As for using the python interpreter, I could add instructions for that ass well.  Really, it would just be running the command `python` from the shell.

**Comment by djw8605** [comment]
Added Instructions for starting the interpreter in 579f7e3

**Comment by tbekolay** [comment]
Looks good to me, thanks!

**Pull request merged**
