### PR TITLE
02-loop.md: Another reason why for loops are useful

### PR DESCRIPTION
**Pull request by GitHub-Sofyan**
Please delete the text below before submitting your contribution. 

Addressed issue #535 - Another reason why for loops are useful.
3 changes
1) Added a third reason, called "Maintenance:"
2) Added the explanation for the third reason.
3) Changed the titles of the two reasons to be in line with the change.

### CODE REVIEW

**Comment by maxim-belkin** [comment]
Thanks, @alee. Let's keep changes to a minimum: please keep those "it does not scale / it is fragile". Another point: I guess you mean "Maintainability" (characteristic of a code), not "Maintenance" (the act of maintaining the software). Please change the wording to (something like): `3. it is not trivial to maintain: ...` I think "maintainability" is a less trivial problem here so let's make it the last point (after fragility).

**Comment by maxim-belkin** [comment]
I think you meant to link to #525, not #535

**Comment by maxim-belkin** [comment]
ping, @GitHub-Sofyan! Please let us know if you can or can not work on this PR.

**Comment by GitHub-Sofyan** [comment]
Greetings Maxin,

My sincere apologies. I was away for the past 10 days. Unfortunately, no I
am not able to as I am currently in the midst of submitting my thesis.

Apologies.

*Cheers*
*Sofyan Sahrom*
"The Eternal Student" <https://sofyansahrom.wordpress.com/>* - "**Always
Learning, Always Growing"*

<https://sg.linkedin.com/in/sofyansahrom>
*****************************************************************
CAUTION: This email message and accompanying data may contain information
that is confidential and subject to legal privilege. If you are not the
intended recipient, you are notified that any use, dissemination,
distribution or copying of this message or data is prohibited. If you have
received this email message in error, please notify us immediately and
erase all copies of this message and attachments. Thank you.

**Comment by maxim-belkin** [comment]
I will take care of this PR. @annefou, I will ask for your review once I implement the changes I think are necessary

**Comment by annefou** [comment]
Ok. Thanks @maxim-belkin

**Comment by maxim-belkin** [comment]
And here it is: piiiiiing! :)

**Comment by maxim-belkin** [comment]
Fixed those two - thank  you.

**Comment by maxim-belkin** [comment]
Thanks, Sofyan!

**Pull request merged**
