### PR TITLE
Instruct solns cmdline

### PR DESCRIPTION
**Pull request by PBarmby**
Initial draft of solutions for 10-cmdline. Doubtless could use improvements, but I was aiming for easy-to-understand, not elegant.

### CODE REVIEW

**Comment by abostroem** [comment]
@PBarmby These look great. Do you think we should reference the code (I'm specifically thinking of readings-07 and readings-08) or just leave it as is?

**Comment by abostroem** [comment]
How were you picturing merging this with #144 ? Should I merge #144 and then this directly after?

**Comment by PBarmby** [comment]
Yeah, makes sense to reference the code files in the instructor solution file. I'll do that for readings-07 and readings-08  and make sure it's there for all of the other ones.
Re: order of this merge and #144. Shouldn't matter since they are from different branches of mine; although both modify instructors.md and add things to code/, there shouldn't be any conflicts.

**Comment by PBarmby** [comment]
OK, above changes done, ready to go.

**Pull request merged**
