### PR TITLE
fig/README.md: add notes about cleaning up SVG files

### PR DESCRIPTION
**Pull request by maxim-belkin**
Adding notes about cleaning up SVG files.

### CODE REVIEW

**Comment by annefou** [comment]
Maybe we should mention that these instructions are valid for Linux and Mac-OSX? Do we need to add some information on which tools need to be installed to manipulate SVG files?

**Comment by maxim-belkin** [comment]
Good points. I will mention that these are Linux/Mac instructions. 

I'm still not sure if we want to have these instructions here or somewhere in a wiki for maintainers... What do you think? I'm afraid contributors might feel overwhelmed with the amount of instructions we have :). Perhaps, we should just say:

> use any tool of your choice to create SVG images. When submitting PNG images, please provide exact instructions how these images were obtained.

**Comment by annefou** [comment]
I like the idea to give some information on how the SVG files were created; it helps to show that we welcome contributions with new or updated SVG files. And of course, anyone is welcome to use any other tools.
If we don't add it in the README file, should we add it in CONTRIBUTING.md?

**Comment by maxim-belkin** [comment]
Thanks for approving this, @annefou! I will make minor updates to the instructions for the tools a bit later.

**Comment by maxim-belkin** [comment]
Consider using only one tool. See instructions here: https://github.com/swcarpentry/python-novice-inflammation/pull/573#issuecomment-418911655

**Comment by slel** [comment]
Thanks for these tips! I propose some slight rephrasing in #623.

**Pull request merged**
